name: publish new release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"
          cache: true
      - run: dotnet --version
      - run: dotnet restore
      - run: dotnet publish -c Release
      - name: Create Release
        uses: ncipollo/release-action@v1.16.0
        with:
          allowUpdates: true
          draft: false
          artifacts: "./bin/**/*.exe"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
